a = 'hi'
a.capitalize()
a.center()
a.count()
a.encode() # orginal to whatever the value is
a.endswith()
a.expandtabs()
a.find()
a.format()
a.format_map()
a.index()
a.isalnum()
a.isalpha()
a.isascii()
ord("A") # turns from string to character (number)
chr(97) # turns from character to string (letter)
a.isdecimal()
